# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region = "eu-west-1"

  default_tags {
    tags = { "Owner" : "platform-team", "Repository" : "eks-zero-trust-blueprint", "Terraform" : "true" }
  }
}
