apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: graviton
spec:
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["arm64"]
    - key: kubernetes.io/os
      operator: In
      values: ["linux"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: node.kubernetes.io/instance-type
      operator: In
      values: ["t4g.medium", "c7g.large", "m7g.large"]
  limits:
    resources:
      cpu: 1000
      memory: 1000Gi
  providerRef:
    name: default
  consolidation:
    enabled: true
  ttlSecondsUntilExpired: 2592000 # 30 days
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  subnetSelector:
    karpenter.sh/discovery: "true"
  securityGroupSelector:
    karpenter.sh/discovery: "true"
  tags:
    Project: "eks-zero-trust"
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 50Gi
        volumeType: gp3
        encrypted: true 